id: P004167
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG10144
  title: དཀོན་མཆོག་སྤྱི་འདུས་ཀྱི་ཆོས་སྐོར།
  author: ''
  volumes:
    a64e2a8f8a9746f5b8b6eba474d8bc79:
      image_group_id: I1KG10146
      title: ''
      volume_number: 1
      total_pages: 500
