id: P004167
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG10144
  title: དཀོན་མཆོག་སྤྱི་འདུས་ཀྱི་ཆོས་སྐོར།
  author: ''
  volumes:
    a64e2a8f8a9746f5b8b6eba474d8bc79:
      image_group_id: I1KG10146
      title: ''
      volume_number: 1
      total_pages: 500
      base_file: v001.txt
